name: 构建Kneip内核

on:
  watch:
    types: [started]

jobs:
  KneipKernel:
    runs-on: ubuntu-latest
    steps:
      - name: 环境准备
        run: |
          sudo apt update -y
          sudo apt-get install -y zip zipalign bc build-essential zip gcc clang libc6 curl libstdc++6 git wget libssl-dev zstd gcc-aarch64-linux-gnu gcc-arm-linux-gnueabi python2 cpio
      - name: 拉取源代码和工具链
        run: |
          git clone https://github.com/brian-tango/msm-4.14.git --depth=1 -b test
          git clone https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86 --depth=1
          mv linux-x86/clang-r428724 clang
          rm -rf linux-x86
      - name: 构建和上传内核
        run: |
          BOARD=TP1803
          git clone --depth=1 https://github.com/zclkkk/AnyKernel3 -b main
          CLANG_DIR=../clang
          export KBUILD_BUILD_USER="zclkkk"
          export KBUILD_BUILD_HOST="Server"
          args="O=../out ARCH=arm64 CC=${CLANG_DIR}/bin/clang CLANG_TRIPLE=aarch64-linux-gnu- CROSS_COMPILE=aarch64-linux-gnu- CROSS_COMPILE_ARM32=arm-linux-gnueabi- LD=${CLANG_DIR}/bin/ld.lld"
          cd msm-4.14
          make ${args} tp1803_defconfig
          make -j16 ${args}
          cd ..
          cp out/arch/arm64/boot/Image.gz-dtb AnyKernel3/
          cp out/arch/arm64/boot/dtbo.img AnyKernel3/
          cd AnyKernel3
          VERSION=KneipKernel_BETA
          7z a -mx9 ${VERSION}.zip *
          zipalign -v 4 ${VERSION}.zip ../${VERSION}_${BOARD}.zip
          cd ..
          curl -sL https://git.io/file-transfer | bash -s beta
          ./transfer trs ${VERSION}_${BOARD}.zip
